### ISSUE TITLE
IndexOutOfBounds when calling MidiEvent.Convert() on data received from UwpMidiInput

### ISSUE THREAD

**Issue by voxoid0** [atsushieno/managed-midi#38]
Hi. I'm getting a IndexOutOfBounds when calling MidiEvent.Convert() on data received from UwpMidiInput . The trigger is that the UWP MidiInPort is reporting that my MIDI device (a Yamaha P-115) is continually sending single-byte messages `0xFE` . Possibly I'm doing it wrong, so here's what I'm doing. I subscribed to `IMidiInput.MessageReceived` event with the following function:

```
        private void MidiInputOnMessageReceived(object sender, MidiReceivedEventArgs args)
        {
            MidiEvent midiEvent = MidiEvent.Convert(args.Data, 0, args.Data.Length).Single();
            ...
        }
```

That first line is where the error occurs, where args.Data is byte[] { 0xFE }. 
For now, in my temporary copy of UwpMidiInput (since I previously couldn't access it from the nuget package), I'm ignoring single-byte messages, though I haven't reviewed the MIDI spec to see if there are valid single-byte messages, but in my case I only care about note on/off events anyway.

**Comment by atsushieno** [comment]
Fnh events seem to be valid MIDI messages. There was a very recent issue regarding them: https://github.com/atsushieno/managed-midi/issues/36

`MidiEvent.Convert()` part of the issue should be fixed in the latest v1.9.1. I just added new tests that ensure that. If it still reproduces please reopen this.
